# Generated by Django 2.2.1 on 2019-05-14 19:37

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('notifyCount', models.IntegerField()),
                ('unreadCount', models.IntegerField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None)),
            ],
        ),
    ]
