# Generated by Django 2.2.1 on 2019-05-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=150, null=True)),
                ('callNo', models.CharField(max_length=20, null=True)),
                ('desc', models.CharField(max_length=250, null=True)),
                ('disabled', models.BooleanField(null=True)),
                ('href', models.CharField(max_length=150, null=True)),
                ('key', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('owner', models.CharField(max_length=150, null=True)),
                ('progress', models.SmallIntegerField()),
                ('status', models.SmallIntegerField()),
                ('title', models.CharField(max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
