def activities():
    return [{"id": "trend-1", "updatedAt": "2019-05-16T11:54:41.953Z",
             "user": {"name": "علی اوجی", "avatar": "/images/avatar/01.jpg"}, "group": {"name": "گروه دوم", "link": ""},
             "project": {"name": "پروژه سوم", "link": ""}, "template": "از @{group} برای @{project}"},
            {"id": "trend-2", "updatedAt": "2019-05-16T11:54:41.953Z",
             "user": {"name": "", "avatar": "/images/avatar/02.jpg"}, "group": {"name": "گروه اول", "link": ""},
             "project": {"name": "پروژه سوم", "link": ""}, "template": "از @{group} برای @{project}"},
            {"id": "trend-3", "updatedAt": "2019-05-16T11:54:41.953Z",
             "user": {"name": "", "avatar": "/images/avatar/03.jpg"}, "group": {"name": "علی اوجی", "link": ""},
             "project": {"name": "گروه چهارم", "link": ""}, "template": "از @{group} برای @{project}"},
            {"id": "trend-4", "updatedAt": "2019-05-16T11:54:41.953Z",
             "user": {"name": "کاربر پنجم", "avatar": "/images/avatar/05.jpg"},
             "project": {"name": "پروژه دوم", "link": ""}, "template": "از @{user} برای @{project}"},
            {"id": "trend-5", "updatedAt": "2019-05-16T11:54:41.953Z",
             "user": {"name": "", "avatar": "/images/avatar/04.jpg"}, "project": {"name": "", "link": ""},
             "comment": {"name": "", "link": ""}, "template": "از @{comment} برای @{project}"},
            {"id": "trend-6", "updatedAt": "2019-05-16T11:54:41.953Z",
             "user": {"name": "", "avatar": "/images/avatar/06.jpg"}, "group": {"name": "", "link": ""},
             "project": {"name": "", "link": ""}, "template": "از @{group} برای @{project}"}]


def data():
    return {"visitData": [{"x": "2019-05-16", "y": 7}, {"x": "2019-05-17", "y": 5}, {"x": "2019-05-18", "y": 4},
                          {"x": "2019-05-19", "y": 2}, {"x": "2019-05-20", "y": 4}, {"x": "2019-05-21", "y": 7},
                          {"x": "2019-05-22", "y": 5}, {"x": "2019-05-23", "y": 6}, {"x": "2019-05-24", "y": 5},
                          {"x": "2019-05-25", "y": 9}, {"x": "2019-05-26", "y": 6}, {"x": "2019-05-27", "y": 3},
                          {"x": "2019-05-28", "y": 1}, {"x": "2019-05-29", "y": 5}, {"x": "2019-05-30", "y": 3},
                          {"x": "2019-05-31", "y": 6}, {"x": "2019-06-01", "y": 5}],
            "visitData2": [{"x": "2019-05-16", "y": 1}, {"x": "2019-05-17", "y": 6}, {"x": "2019-05-18", "y": 4},
                           {"x": "2019-05-19", "y": 8}, {"x": "2019-05-20", "y": 3}, {"x": "2019-05-21", "y": 7},
                           {"x": "2019-05-22", "y": 2}],
            "salesData": [{"x": "1", "y": 498}, {"x": "2", "y": 254}, {"x": "3", "y": 359}, {"x": "4", "y": 957},
                          {"x": "5", "y": 1094}, {"x": "6", "y": 1078}, {"x": "7", "y": 397}, {"x": "8", "y": 657},
                          {"x": "9", "y": 1154}, {"x": "10", "y": 795}, {"x": "11", "y": 1031},
                          {"x": "12", "y": 1181}],
            "searchData": [{"index": 1, "keyword": "-0", "count": 232, "range": 88, "status": 1},
                           {"index": 2, "keyword": "-1", "count": 475, "range": 71, "status": 0},
                           {"index": 3, "keyword": "-2", "count": 940, "range": 50, "status": 0},
                           {"index": 4, "keyword": "-3", "count": 788, "range": 10, "status": 0},
                           {"index": 5, "keyword": "-4", "count": 981, "range": 10, "status": 1},
                           {"index": 6, "keyword": "-5", "count": 293, "range": 39, "status": 0},
                           {"index": 7, "keyword": "-6", "count": 443, "range": 57, "status": 0},
                           {"index": 8, "keyword": "-7", "count": 537, "range": 66, "status": 1},
                           {"index": 9, "keyword": "-8", "count": 462, "range": 53, "status": 1},
                           {"index": 10, "keyword": "-9", "count": 809, "range": 39, "status": 0},
                           {"index": 11, "keyword": "-10", "count": 448, "range": 4, "status": 0},
                           {"index": 12, "keyword": "-11", "count": 44, "range": 9, "status": 1},
                           {"index": 13, "keyword": "-12", "count": 288, "range": 61, "status": 1},
                           {"index": 14, "keyword": "-13", "count": 462, "range": 69, "status": 0},
                           {"index": 15, "keyword": "-14", "count": 780, "range": 54, "status": 1},
                           {"index": 16, "keyword": "-15", "count": 668, "range": 46, "status": 1},
                           {"index": 17, "keyword": "-16", "count": 217, "range": 60, "status": 0},
                           {"index": 18, "keyword": "-17", "count": 131, "range": 29, "status": 1},
                           {"index": 19, "keyword": "-18", "count": 89, "range": 44, "status": 0},
                           {"index": 20, "keyword": "-19", "count": 275, "range": 82, "status": 0},
                           {"index": 21, "keyword": "-20", "count": 239, "range": 64, "status": 0},
                           {"index": 22, "keyword": "-21", "count": 924, "range": 69, "status": 0},
                           {"index": 23, "keyword": "-22", "count": 682, "range": 67, "status": 1},
                           {"index": 24, "keyword": "-23", "count": 384, "range": 61, "status": 1},
                           {"index": 25, "keyword": "-24", "count": 750, "range": 70, "status": 1},
                           {"index": 26, "keyword": "-25", "count": 20, "range": 94, "status": 0},
                           {"index": 27, "keyword": "-26", "count": 28, "range": 32, "status": 1},
                           {"index": 28, "keyword": "-27", "count": 765, "range": 63, "status": 0},
                           {"index": 29, "keyword": "-28", "count": 491, "range": 96, "status": 1},
                           {"index": 30, "keyword": "-29", "count": 2, "range": 96, "status": 0},
                           {"index": 31, "keyword": "-30", "count": 862, "range": 50, "status": 1},
                           {"index": 32, "keyword": "-31", "count": 333, "range": 30, "status": 0},
                           {"index": 33, "keyword": "-32", "count": 781, "range": 18, "status": 0},
                           {"index": 34, "keyword": "-33", "count": 863, "range": 64, "status": 1},
                           {"index": 35, "keyword": "-34", "count": 629, "range": 41, "status": 0},
                           {"index": 36, "keyword": "-35", "count": 109, "range": 29, "status": 0},
                           {"index": 37, "keyword": "-36", "count": 882, "range": 16, "status": 1},
                           {"index": 38, "keyword": "-37", "count": 559, "range": 31, "status": 1},
                           {"index": 39, "keyword": "-38", "count": 422, "range": 89, "status": 1},
                           {"index": 40, "keyword": "-39", "count": 540, "range": 93, "status": 1},
                           {"index": 41, "keyword": "-40", "count": 884, "range": 13, "status": 0},
                           {"index": 42, "keyword": "-41", "count": 164, "range": 91, "status": 0},
                           {"index": 43, "keyword": "-42", "count": 492, "range": 77, "status": 0},
                           {"index": 44, "keyword": "-43", "count": 211, "range": 62, "status": 0},
                           {"index": 45, "keyword": "-44", "count": 809, "range": 5, "status": 1},
                           {"index": 46, "keyword": "-45", "count": 591, "range": 67, "status": 0},
                           {"index": 47, "keyword": "-46", "count": 558, "range": 4, "status": 1},
                           {"index": 48, "keyword": "-47", "count": 203, "range": 27, "status": 1},
                           {"index": 49, "keyword": "-48", "count": 87, "range": 37, "status": 1},
                           {"index": 50, "keyword": "-49", "count": 893, "range": 5, "status": 0}],
            "offlineData": [{"name": "Stores 0", "cvr": 0.8}, {"name": "Stores 1", "cvr": 0.2},
                            {"name": "Stores 2", "cvr": 0.3}, {"name": "Stores 3", "cvr": 0.1},
                            {"name": "Stores 4", "cvr": 0.5}, {"name": "Stores 5", "cvr": 0.4},
                            {"name": "Stores 6", "cvr": 0.6}, {"name": "Stores 7", "cvr": 0.5},
                            {"name": "Stores 8", "cvr": 0.3}, {"name": "Stores 9", "cvr": 0.8}],
            "offlineChartData": [{"x": 1558007682097, "y1": 84, "y2": 91},
                                 {"x": 1558009482097, "y1": 36, "y2": 75},
                                 {"x": 1558011282097, "y1": 102, "y2": 53},
                                 {"x": 1558013082097, "y1": 76, "y2": 104},
                                 {"x": 1558014882097, "y1": 101, "y2": 66},
                                 {"x": 1558016682097, "y1": 75, "y2": 107},
                                 {"x": 1558018482097, "y1": 84, "y2": 33},
                                 {"x": 1558020282097, "y1": 17, "y2": 84},
                                 {"x": 1558022082097, "y1": 30, "y2": 80},
                                 {"x": 1558023882097, "y1": 78, "y2": 22},
                                 {"x": 1558025682097, "y1": 102, "y2": 56},
                                 {"x": 1558027482097, "y1": 99, "y2": 74},
                                 {"x": 1558029282097, "y1": 12, "y2": 97},
                                 {"x": 1558031082097, "y1": 92, "y2": 66},
                                 {"x": 1558032882097, "y1": 79, "y2": 10},
                                 {"x": 1558034682097, "y1": 41, "y2": 82},
                                 {"x": 1558036482097, "y1": 68, "y2": 18},
                                 {"x": 1558038282097, "y1": 25, "y2": 37},
                                 {"x": 1558040082097, "y1": 24, "y2": 109},
                                 {"x": 1558041882097, "y1": 74, "y2": 94}],
            "salesTypeData": [{"x": "ناخالص", "y": 4544}, {"x": "کلی", "y": 3321}, {"x": "جزئی", "y": 3113},
                              {"x": "موارد غیر", "y": 2341}, {"x": "مدیر فناوری اطلاعات", "y": 1231},
                              {"x": "تخفیف", "y": 1231}],
            "salesTypeDataOnline": [{"x": "ناخالص", "y": 244}, {"x": "جزئی", "y": 321},
                                    {"x": "موارد غیر", "y": 311}, {"x": "مدیر فناوری اطلاعات", "y": 41},
                                    {"x": "سایت های دیگر", "y": 121}, {"x": "شبکه های اجتماعی", "y": 111}],
            "salesTypeDataOffline": [{"x": "ناخالص", "y": 244}, {"x": "جزئی", "y": 321},
                                     {"x": "موارد غیر", "y": 311}, {"x": "مدیر فناوری اطلاعات", "y": 41},
                                     {"x": "سایت های دیگر", "y": 121}],
            "radarData": [{"name": "تیمی", "label": "تیمی", "value": 10},
                          {"name": "تیمی", "label": "گروهی", "value": 8},
                          {"name": "تیمی", "label": "خروجی", "value": 4},
                          {"name": "تیمی", "label": "فردی", "value": 5},
                          {"name": "تیمی", "label": "تمام نشده", "value": 7},
                          {"name": "پراکنده", "label": "تیمی", "value": 3},
                          {"name": "پراکنده", "label": "گروهی", "value": 9},
                          {"name": "پراکنده", "label": "خروجی", "value": 6},
                          {"name": "پراکنده", "label": "فردی", "value": 3},
                          {"name": "پراکنده", "label": "تمام نشده", "value": 1},
                          {"name": "شخصی", "label": "تیمی", "value": 4},
                          {"name": "شخصی", "label": "گروهی", "value": 1},
                          {"name": "شخصی", "label": "خروجی", "value": 6},
                          {"name": "شخصی", "label": "فردی", "value": 5},
                          {"name": "شخصی", "label": "تمام نشده", "value": 7}]}


def auth_routes():
    return {"/form/advanced-form": {"authority": ["admin", "user"]}}


def notice():
    return [{"id": "xxx1", "title": "کتاب", "logo": "/icons/01.png",
             "description": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. ",
             "updatedAt": "1398-10-10T00:00:00.000Z", "member": "محسن ریخته گر", "href": "", "memberLink": ""},
            {"id": "xxx2", "title": "پروژه", "logo": "/icons/02.png",
             "description": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. ",
             "updatedAt": "1398-07-24T00:00:00.000Z", "member": "شهاب اوسیوند", "href": "", "memberLink": ""},
            {"id": "xxx3", "title": "زیبا", "logo": "/icons/03.png",
             "description": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. ",
             "updatedAt": "2019-05-16T11:54:41.953Z", "member": "مهسا آقایی", "href": "", "memberLink": ""},
            {"id": "xxx4", "title": "حرفه ای", "logo": "/icons/04.png",
             "description": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. ",
             "updatedAt": "1398-07-23T00:00:00.000Z", "member": "فاطمه بزرگمهر", "href": "", "memberLink": ""},
            {"id": "xxx5", "title": "سریع", "logo": "/icons/05.png",
             "description": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. ",
             "updatedAt": "1398-07-23T00:00:00.000Z", "member": "ترانه خدابنده", "href": "", "memberLink": ""},
            {"id": "xxx6", "title": "انعطاف پذیر", "logo": "/icons/06.png",
             "description": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. ",
             "updatedAt": "1398-07-23T00:00:00.000Z", "member": "ایمان زارع", "href": "", "memberLink": ""}]


def forms():
    return {"message": "Ok"}


def fake_list():
    return [{"id": "fake-list-0", "owner": "علی محسنی ", "title": "کتاب", "avatar": "/icons/01.png",
             "cover": "/images/01.jpg", "status": "active", "percent": 72, "logo": "/icons/01.png",
             "href": "https://a.b.com", "updatedAt": "2019-05-17T14:00:25.050Z",
             "createdAt": "2019-05-17T14:00:25.050Z",
             "subDescription": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم ",
             "description": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. ",
             "activeUser": 175253, "newUser": 1791, "star": 134, "like": 120, "message": 13,
             "content": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. ",
             "members": [{"avatar": "/public/images/list-card.png", "name": "علی محسنی", "id": "member1"},
                         {"avatar": "/public/images/list-card.png", "name": "پیام صبری", "id": "member2"},
                         {"avatar": "/public/images/list-card.png", "name": "مهدی صدر", "id": "member3"}]},
            {"id": "fake-list-1", "owner": "فرزاد یکتا", "title": "پروژه", "avatar": "/icons/02.png",
             "cover": "/images/02.jpg", "status": "exception", "percent": 90, "logo": "/icons/02.png",
             "href": "https://a.b.com", "updatedAt": "2019-05-17T12:00:25.050Z",
             "createdAt": "2019-05-17T12:00:25.050Z",
             "subDescription": "کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد",
             "description": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. ",
             "activeUser": 108484, "newUser": 1182, "star": 159, "like": 158, "message": 16,
             "content": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. ",
             "members": [{"avatar": "/public/images/list-card.png", "name": "علی محسنی", "id": "member1"},
                         {"avatar": "/public/images/list-card.png", "name": "پیام صبری", "id": "member2"},
                         {"avatar": "/public/images/list-card.png", "name": "مهدی صدر", "id": "member3"}]},
            {"id": "fake-list-2", "owner": "امید اکبری", "title": "زیبا", "avatar": "/icons/03.png",
             "cover": "/images/03.jpg", "status": "normal", "percent": 71, "logo": "/icons/03.png",
             "href": "https://a.b.com", "updatedAt": "2019-05-17T10:00:25.050Z",
             "createdAt": "2019-05-17T10:00:25.050Z",
             "subDescription": "در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل",
             "description": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. ",
             "activeUser": 102144, "newUser": 1045, "star": 118, "like": 193, "message": 17,
             "content": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. ",
             "members": [{"avatar": "/public/images/list-card.png", "name": "علی محسنی", "id": "member1"},
                         {"avatar": "/public/images/list-card.png", "name": "پیام صبری", "id": "member2"},
                         {"avatar": "/public/images/list-card.png", "name": "مهدی صدر", "id": "member3"}]},
            {"id": "fake-list-3", "owner": "سعید سلطانی", "title": "حرفه ای", "avatar": "/icons/04.png",
             "cover": "/images/04.jpg", "status": "active", "percent": 76, "logo": "/icons/04.png",
             "href": "https://a.b.com", "updatedAt": "2019-05-17T08:00:25.050Z",
             "createdAt": "2019-05-17T08:00:25.050Z",
             "subDescription": "حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود ",
             "description": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. ",
             "activeUser": 147991, "newUser": 1668, "star": 130, "like": 114, "message": 16,
             "content": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. ",
             "members": [{"avatar": "/public/images/list-card.png", "name": "علی محسنی", "id": "member1"},
                         {"avatar": "/public/images/list-card.png", "name": "پیام صبری", "id": "member2"},
                         {"avatar": "/public/images/list-card.png", "name": "مهدی صدر", "id": "member3"}]},
            {"id": "fake-list-4", "owner": "سهیل شادمان", "title": "سریع", "avatar": "/icons/05.png",
             "cover": "/images/04.jpg", "status": "exception", "percent": 80, "logo": "/icons/05.png",
             "href": "https://a.b.com", "updatedAt": "2019-05-17T06:00:25.050Z",
             "createdAt": "2019-05-17T06:00:25.050Z",
             "subDescription": "برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.",
             "description": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. ",
             "activeUser": 186891, "newUser": 1158, "star": 138, "like": 164, "message": 13,
             "content": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. ",
             "members": [{"avatar": "/public/images/list-card.png", "name": "علی محسنی", "id": "member1"},
                         {"avatar": "/public/images/list-card.png", "name": "پیام صبری", "id": "member2"},
                         {"avatar": "/public/images/list-card.png", "name": "مهدی صدر", "id": "member3"}]}]


def profile_basic():
    return {"basicGoods": [
        {"id": "1234561", "name": "", "barcode": "12421432143214321", "price": "2.00", "num": "1", "amount": "2.00"},
        {"id": "1234562", "name": "", "barcode": "12421432143214322", "price": "3.00", "num": "2",
         "amount": "6.00"},
        {"id": "1234563", "name": "", "barcode": "12421432143214323", "price": "7.00", "num": "4",
         "amount": "28.00"},
        {"id": "1234564", "name": "", "barcode": "12421432143214324", "price": "8.50", "num": "3",
         "amount": "25.50"}], "basicProgress": [
        {"key": "1", "time": "1398-10-25 13:00", "rate": "فروش جز", "status": "processing", "operator": "محمد صدری",
         "cost": "5 ساعت"},
        {"key": "2", "time": "1398-10-25 13:00", "rate": "فروش جز", "status": "success", "operator": "محمد راستی",
         "cost": "1 ساعت"},
        {"key": "3", "time": "1398-10-25 13:00", "rate": "فروش کل", "status": "success", "operator": "حامد ناصری",
         "cost": "3 ساعت"},
        {"key": "4", "time": "1398-10-25 13:00", "rate": "فروش کل", "status": "success", "operator": "کامران فروزان",
         "cost": "30 دقیقه"}]}


def profile_advanced():
    return {"advancedOperation1": [
        {"key": "op1", "type": "ورود از موبایل", "status": "agree", "updatedAt": "1398-10-03  19:23:12", "memo": "-"},
        {"key": "op2", "type": "ورود سیستم", "status": "reject", "updatedAt": "1398-10-03  19:23:12", "memo": "بله"},
        {"key": "op3", "type": "ورود از موبایل", "status": "agree", "updatedAt": "1398-10-03  19:23:12", "memo": "-"},
        {"key": "op4", "type": "ورود از سیستم", "status": "agree", "updatedAt": "1398-10-03  19:23:12", "memo": "بله"},
        {"key": "op5", "type": "ورود از سیستم", "status": "agree", "updatedAt": "1398-10-03  19:23:12", "memo": "-"}],
        "advancedOperation2": [
            {"key": "op5", "type": "ورود از سیستم", "status": "agree", "updatedAt": "1398-10-03  19:23:12",
             "memo": "-"}]}


def notices():
    return [{"id": "000000001", "avatar": "images/avatar/01.jpg", "title": "از طرف دوست عزیز", "datetime": "1398-08-09",
             "type": "notification"},
            {"id": "000000006", "avatar": "images/avatar/02.jpg", "title": "از طرف دوست عزیز", "description": "توضیح ",
             "datetime": "1398-08-07", "type": "message", "clickClose": True},
            {"id": "000000009", "title": "رویداد اول",
             "description": "چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم ", "extra": "انجام نشده",
             "status": "todo", "type": "event"}, {"id": "000000010", "title": "رویداد دوم",
                                                  "description": "چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم ",
                                                  "extra": "انجام شده", "status": "urgent", "type": "event"},
            {"id": "000000011", "title": "رویداد سوم",
             "description": "چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم ", "extra": "در حال انجام",
             "status": "doing", "type": "event"}]
